import Foundation

public enum OnboardingTemplate: String, CaseIterable, Sendable {
    case morning, evening, manual
}

public struct OnboardingEntry: Codable, Equatable, Identifiable, Sendable {
    public let id: UUID
    public var form: HabitFormDraft

    public init(form: HabitFormDraft) { id = UUID(); self.form = form }
}

/// IDs are allocated when a draft is chosen, never regenerated by confirmation.
/// This draft does not write habits; the store's atomic confirmation is the only Apply path.
public struct OnboardingDraft: Codable, Equatable, Sendable {
    public var entries: [OnboardingEntry]

    public init(template: OnboardingTemplate, now: Date = Date(), calendar: Calendar = .current) {
        let definitions: [HabitDefinition]
        switch template {
        case .morning:
            definitions = [
                HabitDefinition(title: "Stretch", normalTarget: "5 minutes", lightTarget: "1 minute",
                                dayPart: .morning, recurrence: .weekly(weekdays: Set(1...7))),
                HabitDefinition(title: "Plan my day", normalTarget: "Choose 3 priorities", lightTarget: "Choose 1 priority",
                                dayPart: .morning, recurrence: .weekly(weekdays: Set(1...7)))
            ]
        case .evening:
            definitions = [
                HabitDefinition(title: "Read", normalTarget: "10 pages", lightTarget: "2 pages",
                                dayPart: .evening, recurrence: .weekly(weekdays: Set(1...7))),
                HabitDefinition(title: "Prepare for tomorrow", normalTarget: "Prepare tomorrow's essentials", lightTarget: "Set out one thing",
                                dayPart: .evening, recurrence: .weekly(weekdays: Set(1...7)))
            ]
        case .manual:
            definitions = [HabitDefinition(title: "", normalTarget: "", dayPart: .morning,
                                           recurrence: .weekly(weekdays: Set(1...7)))]
        }
        entries = definitions.map { OnboardingEntry(form: HabitFormDraft(definition: $0, now: now, calendar: calendar)) }
    }
}

public struct OnboardingProgress: Codable, Equatable, Sendable {
    public enum Status: String, Codable, Sendable { case unseen, inProgress, skipped, finished }
    public let version: Int
    public var status: Status
    public var draft: OnboardingDraft?

    public init() { version = 1; status = .unseen; draft = nil }
    public func shouldOfferAutomatically(hasExistingHabits: Bool) -> Bool {
        !hasExistingHabits && status == .unseen
    }
}
